# Generated by Django 3.2.16 on 2023-01-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['id'], 'verbose_name': 'medidor', 'verbose_name_plural': 'medidores'},
        ),
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_date', models.DateTimeField()),
                ('measure', models.PositiveIntegerField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_meters.meter')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
                'ordering': ['-registry_date'],
            },
        ),
    ]
